// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoDOWj-29MfM44pVbS3MdOrM7HVu4uz9M',
    appId: '1:273682140685:web:8ea835816966a53b994f44',
    messagingSenderId: '273682140685',
    projectId: 'todo-clean-acrhi',
    authDomain: 'todo-clean-acrhi.firebaseapp.com',
    storageBucket: 'todo-clean-acrhi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7k7RqBDYc1yzn8fNI4JrZTrXJI39XGhI',
    appId: '1:273682140685:android:59589f2845718582994f44',
    messagingSenderId: '273682140685',
    projectId: 'todo-clean-acrhi',
    storageBucket: 'todo-clean-acrhi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyY-SiBwCUnRGUrZZsd3lpmaLp4paj3xY',
    appId: '1:273682140685:ios:5f4c1cd172948fa9994f44',
    messagingSenderId: '273682140685',
    projectId: 'todo-clean-acrhi',
    storageBucket: 'todo-clean-acrhi.appspot.com',
    iosBundleId: 'com.example.toDoListCleanArchitecture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyY-SiBwCUnRGUrZZsd3lpmaLp4paj3xY',
    appId: '1:273682140685:ios:5f4c1cd172948fa9994f44',
    messagingSenderId: '273682140685',
    projectId: 'todo-clean-acrhi',
    storageBucket: 'todo-clean-acrhi.appspot.com',
    iosBundleId: 'com.example.toDoListCleanArchitecture',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoDOWj-29MfM44pVbS3MdOrM7HVu4uz9M',
    appId: '1:273682140685:web:0da62e5e7459b503994f44',
    messagingSenderId: '273682140685',
    projectId: 'todo-clean-acrhi',
    authDomain: 'todo-clean-acrhi.firebaseapp.com',
    storageBucket: 'todo-clean-acrhi.appspot.com',
  );
}
