// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvBnMmUjWSieWwdEV2HNCWldq5uCSgMSo',
    appId: '1:1041684792099:web:96ac5836a07878c9910296',
    messagingSenderId: '1041684792099',
    projectId: 'todo-clean-archi',
    authDomain: 'todo-clean-archi.firebaseapp.com',
    storageBucket: 'todo-clean-archi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUskoEYNxNG9Yne38fz1zmuixP62Oce3I',
    appId: '1:1041684792099:android:f476f0a5ebe115fd910296',
    messagingSenderId: '1041684792099',
    projectId: 'todo-clean-archi',
    storageBucket: 'todo-clean-archi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM8T_LbvnMVv95Rax79k9qhLxiol4vf4E',
    appId: '1:1041684792099:ios:720c755df4c11034910296',
    messagingSenderId: '1041684792099',
    projectId: 'todo-clean-archi',
    storageBucket: 'todo-clean-archi.appspot.com',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM8T_LbvnMVv95Rax79k9qhLxiol4vf4E',
    appId: '1:1041684792099:ios:720c755df4c11034910296',
    messagingSenderId: '1041684792099',
    projectId: 'todo-clean-archi',
    storageBucket: 'todo-clean-archi.appspot.com',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvBnMmUjWSieWwdEV2HNCWldq5uCSgMSo',
    appId: '1:1041684792099:web:ea119d4d257afadc910296',
    messagingSenderId: '1041684792099',
    projectId: 'todo-clean-archi',
    authDomain: 'todo-clean-archi.firebaseapp.com',
    storageBucket: 'todo-clean-archi.appspot.com',
  );
}
